bot_token = "1678101756:AAHmN1qq2mXYBzlZXGF_eO6g394QAa0mETY"
photo_id = {'main_menu':'AgACAgIAAxkBAAICJmBcfAyq1qO25FHQdiUFUVcMNjgLAAL0sTEbFuzgSr_a_D89ChTlQv4Eny4AAwEAAwIAA3gAA3s5AAIeBA',
            'backery':'AgACAgIAAxkBAAICoGBcgsDTr_bD4E9verqmuB4GwJRzAAIBsjEbFuzgSlS90BZDOiZ5qhSSoS4AAwEAAwIAA3gAA3Q9AAIeBA',
            'garnish':'AgACAgIAAxkBAAIDzGBc6OEyzR2FaWXs7iF3b4VJ-gyJAAL0sjEbFuzgSjyOLW2DWg6UwiCVoS4AAwEAAwIAA3kAAwI_AAIeBA',
            'hot_meat':'AgACAgIAAxkBAAIDzmBc6hDSKkY50AmbXaGpoRhTznTjAAL3sjEbFuzgSqlcOyjT8XlcdDtMoi4AAwEAAwIAA3gAAx1PAAIeBA',
            'drink':'AgACAgIAAxkBAAID0GBc6lG0h46YLaSFeQJUxvoDZzcxAAL4sjEbFuzgSr3baSgxRoSp5LYQoi4AAwEAAwIAA3gAA5lCAAIeBA',
            'salat':'AgACAgIAAxkBAAID0mBc6mKveBoAAR4WQMfv7sK1nHI87QAC-bIxGxbs4Eq3Qt1w-Q46kzv6aZcuAAMBAAMCAAN5AAOkhAcAAR4E',
            'cold_eat':'AgACAgIAAxkBAAIDvmBc2Fah1CgMXppNIG_3N4z-kViVAAIksjEbl67oSkL-DvMUkq-dB4HSoi4AAwEAAwIAA3kAAz8-AAIeBA',}